### ISSUE TITLE
breaks completely on now-deprecated DjangoRESTFramework call

### ISSUE THREAD

**Issue by mosbasik** [sheppard/django-github-hook#11]
All hook requests appear to result in this error message response:

>NotImplementedError at /hook/
>`request.DATA` has been deprecated in favor of `request.data` since version 3.0, and has been fully removed as of version 3.2.

This project's dependencies include DjangoRESTFramework with no version specification and the current version of DjangoRESTFramework is 3.2.x.

At least one of the errors is located in `github_hook/views.py`, line 19:

>/sites/virtualenvs/moviepicker/lib/python2.7/site-packages/github_hook/views.py in post
>                    payload = json.loads(request.DATA.get('payload', "{}")) 

I'm attempting to work around this by installing DjangoRESTFramework 3.1.3 first and installing this project afterwards, but haven't succeeded yet.

I don't know if this project is still alive, but if the fix is as simple as changing the call case, I could probably fix this myself and submit a PR.  Don't think I have time atm though.

**Comment by sheppard** [comment]
Thanks for reporting this!  This project is currently dormant but I will be updating it eventually.  PRs are always welcome.

**Comment by sheppard** [comment]
Fixed in version [0.2.0](https://github.com/sheppard/django-github-hook/releases/tag/v0.2.0)
