### ISSUE TITLE
ImportError: cannot import name 'patterns'

### ISSUE THREAD

**Issue by balinabbb** [sheppard/django-github-hook#15]
Since Django 1.8 patterns is deprecated, and now its removed.
You could simply make your urls.py like:
`from django.conf.urls import url`

instead of

`from django.conf.urls import patterns, url, include`

Those references are not used anyway.

**Comment by jdn5126** [comment]
Fixed by f5dbb52e878383288312017697dd1f72ca86c705

**Comment by sheppard** [comment]
And released as v0.2.1.  Thanks!
